### ISSUE TITLE
Enhancement Opportunity basemaps.js mapStartBasemap not being honored

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#176]
To repo this issue

viewer.js

``` javascript
        mapOptions: {
            basemap: 'hybrid',
            center: [-84.1652, 39.4531],
            zoom: 11,
            sliderStyle: 'small'
        },
```

basemaps.js

``` javascript
        map: true,
        //must be either 'agol' or 'custom'
        mode: 'agol',
        title: 'Basemaps',
        // must match one of the basemap keys below
        mapStartBasemap: 'hybrid',
        //basemaps to show in menu. define in basemaps object below and reference by name here
        // TODO Is this array necessary when the same keys are explicitly included/excluded below?
        basemapsToShow: ['streets', 'satellite', 'hybrid', 'topo', 'lightGray', 'gray', 'national-geographic', 'osm', 'oceans'],
```

In this case hyrbid will show when app loads, but then streets will show. It would appear that `mapStartBasemap` is not being honored. In addition, it seems like it is showing the first basemap in the `basemapsToShow` array. I say this because if I move 'hybrid' to the first item in the array the hybrid will show when app finishes loading.

**Comment by marhensa** [comment]
hm.. why we have to set two basemap in different config file?
and we can't use custom basemap without it blinks first to one of those agol basemap.

for example, 
i have custom basemap named "xxx", and i already set in basemap.js to use custom basemap,
and set mapStartBasemap to use xxx

but in viewer.js I cant use that xxx custom basemap, 
it has to be one of those agol basemap (streets, sattellite, etc).

and because of that, 
those agol basemap will flash few seconds, then my xxx custom basemap starts loading.

i can't use agol basemap because it's uninformative and lack of data in my country.
i have to use my own basemap.

any suggestion, and solution about this?

thank you... :)
