### ISSUE TITLE
Expand and collapse Vector and Overlay layers in the LayerControl Widget

### ISSUE THREAD

**Issue by geoggeek** [cmv/cmv-app#300]
In the LayerControl Widget, `vectorLabel` and `overlayLabel` allow the vector and overlay layer groups to be labelled when `separated: true`. If there are a lot of the two types of layers, it would be useful to be able to collapse or expand the two groups by clicking on the label. This would save space in the left-hand pane when the layers are collapsed.

**Comment by roemhildtg** [comment]
> If there are a lot of the two types of layers, it would be useful to be able to collapse or expand the two groups by clicking on the label.

This is implemented in cmv2.0

**Comment by tmcgee** [comment]
@roemhildtg I did not know this was added to 2.0. Can you point me to the commit?

**Comment by roemhildtg** [comment]
Isn't this asking about expanding layers by clicking on the label?

**Comment by tmcgee** [comment]
I believe the question is about expanding/collapsing the entire `Vector` or `Overlay` group, not an individual layer. Do we support that?

**Comment by roemhildtg** [comment]
I guess I'm mot sure what you mean by overlay and vector groups. The only thing I can find on that is https://developers.arcgis.com/javascript/3/jsapi/overlaylayers-amd.html and the vector tiles.

**Comment by tmcgee** [comment]
@roemhildtg 

This issue is referring to the configuration options (`separated`, `vectorLabel`, and `overlayLabel`) for the layerControl widget as per the [documentation](https://docs.cmv.io/en/latest/widgets/LayerControl/).

These options allow you to group all the `vector` layers (non-graphic layers) together showing a label for that group of layers and  group all `overlay` layers (graphic layers) together showing a label for that group of layers. The request is to be able to expand/collapse those two groups. That makes it easier to navigate the layerControl when there are a lot of layers in one or both groups.

Hopefully that helps clarify. I don't think we support that expand/collapse ability today.

As an aside, being able to configure layer groups (with expand/collapse) is what we should consider for a  future enhancement. Further: the 4.x API completely removes the artificial separation of graphic and non-graphic layers so layers can be freely re-ordered and grouped regardless of the layer type.

**Comment by roemhildtg** [comment]
Oh, that certainly helps. Nope we don't support this today. I had never used that feature apparently 🙁 
![image](https://cloud.githubusercontent.com/assets/5471079/24523150/b2e469a4-1557-11e7-8454-6a7a5d930a46.png)

And yes, I agree. I'm not sure it pays to implement this feature in 3.x since the new 4.x group layers will be a different implementation altogether. Should we label as wont fix?
