### ISSUE TITLE
Modify the results grid to include additional information?

### ISSUE THREAD

**Issue by laceys** [cmv/cmv-app#338]
Hello,
I'm trying to have results of multiple fields populate without having to click on the map for identify results.  I was thinking that if I could have the result grid populate it would eliminate that one click and the information would present immediately.  Is this possible?  

Thank you,
Lacey

**Comment by DavidSpriggs** [comment]
@laceys I believe you talking about the find widget correct? If so please see issue #213. This is not possible because the find task does not return all attributes, this is by design in arcgis server. You could however do a query after the find result returns to fetch the rest of the attributes and display them in the table. This would be seamless to the user.
