### ISSUE TITLE
The FIND function in the cmv don t work on the Ipad, you are not able to select the query?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#358]
On the I pad, I try to use the find, I have many find query to select, when I touch the arrow I saw all my choices but I am not able to select witch one I want, the window seam not sensitive with my finger to select the query I want, try by your self the find on the I pad with the site:
  http://gis.icao.int/icaoviewernew/
its working good on a desktop, in my mind because its bootstrap I think its will be compatible with the touch screen?
![findipad](https://cloud.githubusercontent.com/assets/6784515/5879006/820181be-a2f9-11e4-92be-50f2059a435b.jpg)
Many thanks for your support...

**Comment by tmcgee** [comment]
@GilbertLasnier It is odd that it doesn't work on the iPad. I just sent the link to your application to my android phone and it works there.

There have been some oddities reported specific to Apple devices. These related to the z-order of different screen elements. Perhaps that is what is going on here and the list of choices is visible but not touchable because some other HTML element (invisible) is in the way.  I do not have an iPad to test. Perhaps others with apple devices can confirm that it is occurring for them as well - both in your application and the [cmv demo app](http://demo.cmv.io/viewer).

P.S. For clarification, the [Bootstrap](http://getbootstrap.com/) JavaScript framework is not involved here. I can definitely understand the confusion though. We use a modified dojo theme called "dbootstrap" which gives the app a "bootstrap like" appearance but that is strictly the visual look. The touch capabilities have nothing to do with the Bootstrap framework or the dbootstrap theme. These touch events are handled by the dojo framework and/or by the mobile browser turning touches into emulated mouse clicks.

**Comment by LarryStout** [comment]
It works for me on an iPad running iOS 8.1.2.  I was able to look up the Palm Springs Airport (PSP).

Larry

[cid:image001.jpg@01D03710.B27A0550]

**Comment by GilbertLasnier** [comment]
Many thanks to you booth
now i know that its working good on an android and i must update the IOS to 8.1.2
i think i have just 8.0
 Merci a vous deux, have a good day
