### ISSUE TITLE
Editing the TOC

### ISSUE THREAD

**Issue by laceys** [cmv/cmv-app#372]
I'm trying to reformat the Find and Identify tools in the TOC.  The map is going to be embedded into a website and the TOC had to be narrowed, which messed up all of the formatting.  I've tried looking through the code but am unsure of where I can alter the size of the buttons for "search" and "clear" and take out the checkbox for Find exact matches (removal of the div from the Find.html breaks the widget).  Removal of the Identify button in the TOC without affecting the click on map to identify features would be optimal too. 

Thanks for your time,
Lacey

**Comment by tmcgee** [comment]
@laceys I suspect you can do everything you want using custom CSS for your app. No need to modify the CMV code for the widgets themselves. Inspect the various DOM elements like the Find buttons and checkbox to see what CSS classes you should be focusing on.

I'm not sure what `Identify Button` you are referring to. There isn't an Identify button in the core CMV widgets. Is this a custom widget?

And for clarity, I believe that you mean left side pane, not TOC. The reason for the clarity is that there used to be a widget called "TOC" that was replaced by the layerControl widget.

**Comment by laceys** [comment]
Good afternoon Tim,
Where would I find the custom CSS in the CMV?  Although I can find the DOM
elements that are used in the HTML files I'm unsure of where those DOM
files reside in the CMV application or the dijit/form/Form as there are no
"Forms" folders or files in the dijit folder and there is no code in the
leftContent.html.

I meant to say Identify drop down in the left side pane. Trying to set it
to false in the viewer.js for either include or type it removes the
functionality for clicking on the map and identifying layers in the popup.

You are correct on the TOC/ left side pane error.
This is what I'm trying to correct.  Currently I'm using Notepad++ to view
and change code.   Thanks again for your help!

[image: Inline image 2]

**Comment by tmcgee** [comment]
For they Identify widget, it sounds like you want to remove the UI altogether since the dropdown is the only UI and does resize to the sidebar. Just set the type to `invisible` and the Identify functionality will continue working for ALL layers. The UI is only there to pick a single layer for identifying.

As far as custom CSS, if you have only a single app, you can add your custom CSS to the [main.css](https://github.com/cmv/cmv-app/blob/master/viewer/css/main.css) file for your app. If you have multiple apps that use the main.css file for a common look and feel (that's what I do), you can create and include a separate css file. I call mine `app.css` so it is clear that it is specific to the one app.

As far as a `Forms` folder, I think you mean `Form` and are referring to dijits within the dojo framework. For this exercise, you should not need to bother with that. Just inspect to get the proper DOM nodes to target, look at the classes that have and override those classes in your own css classes with the same names.

**Comment by laceys** [comment]
Thank you Tim,

Setting the type: to invisible was exactly what was needed.

Creating a CSS requires a web software suite, such as Dreamweaver,
correct?  I do not have access to software like that and am trying to
modify what is in the various CSS files included in the CMV.  I just need
to set the alignments of the buttons, the results text as well as the first
zoom level for the record returned in the find UI.  The CMV has been so
well organized it's been pretty easy to do the customization that I've
needed to do up to this point, but on this part I'm stumped and have
limited resources.

**Comment by tmcgee** [comment]
A CSS file like the JavaScript and HTML files is just text and can be edited with Notepad, Notepad++ or any text editor. Special software like DreamWeaver is not required.

**Comment by laceys** [comment]
Thank you Tim.  I've learned a lot from you today, looks like I still have
a ways to go.

**Comment by tmcgee** [comment]
@laceys glad I could help.
