### ISSUE TITLE
Restrict CMV to extent

### ISSUE THREAD

**Issue by jtorresleon** [cmv/cmv-app#399]
Hi Everybody,
I am wondering whether I can set a maximum extent in CMV so that the user cannot leave certain region (limit extent) on the map. something similar to this example

http://jsfiddle.net/gh/gist/library/pure/6050806/

Thanks!

**Comment by tmcgee** [comment]
@jtorresleon Try adding this simple widget to your app:

``` javascript
maxExtent: {
    include: true,
    id: 'maxExtent',
    type: 'invisible',
    path: 'dijit/_WidgetBase',
    options: {
        map: true,
        startup: function () {
            var maxExtent, lastExtent;
            this.map.on("extent-change", function (args) {
                if (!maxExtent) {
                    maxExtent = args.extent;
                    lastExtent = maxExtent;
                }
                if ((args.extent.xmin < maxExtent.xmin) ||
                  (args.extent.ymin < maxExtent.ymin)  ||
                  (args.extent.xmax > maxExtent.xmax) ||
                  (args.extent.ymax > maxExtent.ymax) ) {
                    this.setExtent(lastExtent);
                    console.log("max extent reached, rolling back to previous extent");
                } else {
                    lastExtent = args.extent;
                }
            });
        }
    }
}
```

**Comment by DavidSpriggs** [comment]
@tmcgee Brilliant implementation! Love it!

**Comment by jtorresleon** [comment]
Awesome!, thanks a lot. fast answer

**Comment by gobsmack** [comment]
This is really neat. I had no idea you could create a widget on the fly like that. But, now that I see it, it makes perfect sense. Like you said in the reference, a widget would usually be better, but it's nice to know this is possible.

**Comment by tmcgee** [comment]
@jtorresleon here's a refined widget config options file that I implemented for a client. It is used as a separate file so the the config above would be changed to something like `options: 'config/maxExtent'`. 

``` javascript
define([
    'dojo/_base/lang'
], function (lang) {
    return {
        map: true,
        maxExtent: null,
        lastExtent: null,
        startup: function () {
            this.map.on('extent-change', lang.hitch(this, 'checkExtent'));
            this.setMaxExtent();
        },
        setMaxExtent: function () {
            if (!this.maxExtent) {
                this.maxExtent = this.map.extent;
                this.lastExtent = this.maxExtent;
            }
        },
        checkExtent: function (args) {
            this.setMaxExtent();
            if (!this.maxExtent.intersects(args.extent)) {
                this.map.setExtent(this.lastExtent);
            } else {
                this.lastExtent = args.extent;
            }
        }
    };
});
```

One change is the use of `intersects` method to check if any part of the current map extent is within the max xxtent. This allows the user to wander a little bit further to the edges of the max extent but never completely outside.

Relative to your new question on March 24th, you can set the `maxExtent` property in the config to an actual extent instead of using the map's initial extent. If you did that, you could completely remove the calls to the `setMaxExtent` method but there's no harm in leaving them in there.

**Comment by DavidSpriggs** [comment]
Just a reminder that these types of questions should be posted here:
https://gis.stackexchange.com/questions/tagged/configurable-map-viewer
