### ISSUE TITLE
Widgets Need to Access Global Configuration: How?

### ISSUE THREAD

**Issue by gobsmack** [cmv/cmv-app#413]
I feel like we've touched on this issue before (e.g. #363). And, I think it's been addressed in the "futures" branch of CMV. Until then, what's a really clean way to provide global configuration, including the operationalLayers, to the widgets?

I've done some pretty crazy things already. 
* For some server side variables, I just created a window.xxx variable, and checked window.xxx in my widget. Yikes. 
* For some querystring variables, I pull them right from the URL in the widget. But, it would be cleaner to put the querystring into the config, and then the widget can access the config.
* I've thought about storing global variables using dojo/_base/config. Haven't done it yet.

It seems like the best thing to do would be to pass the whole appConfig into the widget while those widgets are being constructed. But, I'm trying to avoid changing the core.

Has anybody else dealt with widgets accessing global configuration, or the opertionalLayers, using a different approach?

**Comment by DavidSpriggs** [comment]
@gobsmack For now simply add an appModel class that is loaded first by the controller and initial props set there, like your config with set(). Then any widget can later load the appModel and get() and set() props on it as well. This will be coming out of the box soon in cmv but for now you can just include it yourself.
See here for an example:
https://github.com/cmv/cmv-app/blob/add-models/viewer/js/viewer/models/layerModel.js
I'm linking to the LayerModel because its the simplest implementation. Use this as a starting point, it shows the singleton pattern which is the magic.

**Comment by gobsmack** [comment]
Very nice! That's exactly what I need. Much cleaner than passing in the config. The appModel is going to be GREAT addition. Having the ability to access a widget like that will really streamline the menu that I created. 

Definitely some creative people working on CMV.

**Comment by DavidSpriggs** [comment]
Thanks. I came up with the appModel concept here: 
https://github.com/DavidSpriggs/dojo-esri-app
This example also shows how to use watch() on the model as well, very powerful.
