### ISSUE TITLE
How to stop the download via the arcgis rest and keep the identify working in CMV

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#428]
I CLOSE THE QUERY AND THE DATA  IN THE ArcGIS Server Capabilities BECAUSE EVERYBODY STEAL MY DATA...AND ITS WORK NOBODY ARE ABLE TO DOWNLOAD MY DATA...
DO YOU KNOW IF THERE IS A WAY TO SHOW THE IDENTIFY INFO FOR A LAYER IN CMV
WHEN YOU HAVE CLOSE THE  QUERY AND THE DATA ?
DO YOU HAVE A SOLUTION AGAINST THE rest  Capabilities
For the issue 305 Disable popups for no information...
I follow DAVID
 https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L99
and its work there is no info for the layer FIRMSD when I select
}, {
			type: 'dynamic',
			url: 'http://GIS.ICAO.INT/ArcGIS/rest/services/FIRMSD/MapServer',
			title: 'ICAO FIR',
			options: {
				id: 'ICAOFIR2014',
				opacity: 1.0,
				visible: true,
				imageParameters: imageParameters
			
			},
			identifyLayerInfos: {
                layerIds: []
            }
So I have no info and nobody are able to stool the data, but the IDENTIFY doesn't work

**Comment by DavidSpriggs** [comment]
@GilbertLasnier You have to have query enabled in order to use the identify method of a map service.

**Comment by GilbertLasnier** [comment]
Thanks for you answer
I know all that since the beginning... 
its not the question... its how to put data in cmv that work with the identify without the possibility to use the rest query under that services to steal that layer ICAOFIR that we sale...

**Comment by roemhildtg** [comment]
I think your solution would be to make that map service protected with a user name and password and then use a proxy to access those services from your web app.

**Comment by GilbertLasnier** [comment]
I make with the server windows 2008r2 IIS 7 some services with authentication required like https: with gis services like  https://gis.icao.int/epassportEDIT 
But I never make a map service protected, I try long time ago in arcgis manager but at the end; I am not able to see nothing, do you have an other way to do that or that way is OK, or send me a link to explain how to do!! THE FIRST QUESTION was how to show a layer and protect in the same time against piracy...
Many thanks for you answer

**Comment by tmcgee** [comment]
@GilbertLasnier As @roemhildtg the suggested practice is to secure your services. Using ESRI's resource proxy or other means, you can control which urls (your applications) can access the services through the proxy. This will greatly reduce the unauthorized traffic. I intentionally say "greatly reduce" instead of "completely eliminate" because I would never, ever guarantee that determined individual could not hack around a proxy service. ;)

I am saying that it is definitely possible to secure the service. How to configure the services, the proxy and implement those best security practices is way outside the scope of supporting cmv.
