### ISSUE TITLE
create new featureLayer after load, only when needed

### ISSUE THREAD

**Issue by AllisonBell99** [cmv/cmv-app#430]
I have a map service which has over a hundred layers that I load as a dynamic operational layer when the app loads. But I need some of the feature layer capabilities to query related records and to get field coded value domains. Is there a way to load a feature layer inside of a widget when it's in use so that it will only be created if needed? I have tried just using the arcgis javascript api for feature layer, but I get errors when the app loads. Or alternately, is there an easy way to load them all as feature layers when the app loads without listing all of them out in the config?

**Comment by DavidSpriggs** [comment]
@AllisonBell99 There is nothing out of the box directly to support this. This is all possible with some custom code or widget however. If you are just after domains you can simply do a request to the layer endpoint asking for json, no feature layer needed. Same for related records. You could also use a feature layer, created on demand, remember, you don't have to add a feature layer to the map in order to use it. The Esri team does this all the time in the API.

For help with architecting a custom widget I would recommend posting a question to [gis stack exchange](https://gis.stackexchange.com/questions/tagged/configurable-map-viewer). We try to limit Github just to bugs on existing code.

**Comment by AllisonBell99** [comment]
thanks David, I tried adding a featurelayer again and it worked. I was just using = new FeatureLayer(url) before, now I have = new esri.layers.FeatureLayer(url) and it worked as I expected. Sorry I am new to javaScript and am still getting used to the declare statements, objects and variables. Thanks for your help!

**Comment by DavidSpriggs** [comment]
@AllisonBell99 Glad you got it working! As a rule, don't ever use the esri global object (esri.layers.FeatureLayer). Instead add the class to your dependency list like this example: https://developers.arcgis.com/javascript/jssamples/fl_ondemand.html

**Comment by AllisonBell99** [comment]
I added the dependency like the example, and got it to work, however it didn't have all of the featureLayer information (like fields) I think because it wasn't loaded in the map. So I followed your original suggestion of using the json from the endpoint with dojo/request/xhr and that seems to have what I need. Thanks again for your help!

**Comment by btfou** [comment]
@AllisonBell99 FYI...Creating a feature layer object should have all the feature layer info like fields whether added to the map or not. I switched from making the json endpoint request to using FeatureLayer to get layer info not to long ago for a couple widgets designed around specific feature services. There's so much more you can do with a feature layer with much less code like getting counts and object ids. Don't give up on it!
