### ISSUE TITLE
Tiled layers don't display in print output legend

### ISSUE THREAD

**Issue by taran03** [cmv/cmv-app#438]
I'm unable to get my tiled map services to render in the print output's legend.  Specifically, I have a contour data set that I've cached to improve drawing performance.  The layer's symbology displays in the layer control widget (see screen capture), but won't draw in the print output's legend.  Has anybody else encountered this? Any recommended solutions? Thanks!

![image](https://cloud.githubusercontent.com/assets/8386074/8837913/a86eb40c-308e-11e5-8838-e5b8d793c4d6.png)

**Comment by tmcgee** [comment]
Not sure if this is exactly the same issue but it sounds similar: https://geonet.esri.com/message/396203#396203

**Comment by roemhildtg** [comment]
I've had issues before where the legend overflows because there are too many items. I'm not sure how many layers you have in your printout, but this could be related the issue. Our basemap consisted of 7 or 8 layers at several different scales and whenever the basemap was turned on the printout would either overflow the legend items or the legend wouldn't show up at all. 

To work around this we implemented [`legend layers`](https://developers.arcgis.com/javascript/jsapi/legendlayer-amd.html) and forced the basemap to not appear in the legend so that the other layer would. You may want to do the same, but include the basemap layer as well.

**Comment by cananiculi** [comment]
i also have issue with printing... i would like to show all my operational layer's legend on the print template.. how can i do that?can i embedded legend image or other image on the template ?

**Comment by roemhildtg** [comment]
@cananiculi, do you want to show only the operational layers? Or are you just asking how to include a legend in general? Inserting a legend is the same as you would normally. It will just be empty since you don't have any layers in your print template.

**Comment by cananiculi** [comment]
@roemhildtg, actually i want to customize the print template....i want to show legend of my operational layer and and put some image and text of possible...i trying alter the code but nothing happen....can you assist and guide me

**Comment by roemhildtg** [comment]
The first step to customizing print templates is to publish a custom geoprocessing service. [have you done this?](http://video.esri.com/watch/1058/arcgis-for-server-101-printingtools-service-tutorial)

**Comment by cananiculi** [comment]
@roemhildtg, printed PDF don't show any legend even i checked "Include legend" checkbox. do you have any idea why?
![capture](https://cloud.githubusercontent.com/assets/4666543/11065722/e039563a-87ff-11e5-9719-b9dd459bdaf7.PNG)

**Comment by roemhildtg** [comment]
Perhaps try it with a really simple example. Try exporting a printout when only one layer with one symbol is turned on in the map. This will rule out the issue where the legend overflows and nothing gets displayed.
