### ISSUE TITLE
Basemap zoom

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#439]
Any ideias about why I cannot zoom over 200m on the osm (and any other) baselayer? I can zoom to 20m on osm official site.
I even tried setting some lods on viewer config's ```mapOptions```.

**Comment by tmcgee** [comment]
Usually this has to do with limitations within the API and you have to trick it. A frequent trick is to create an empty map service with the desired zoom levels and use this as your basemap in the `mapOptions`

The best way to test your map options is to use a sample such as this one: http://developers.arcgis.com/javascript/sandbox/sandbox.html?sample=map_simple

If you still are having issues, post your mapOptions here.

**Comment by friendde** [comment]
I added a note about this topic last year in the CMV docs. See if this helps you outhttp://docs.cmv.io/en/1.3.4/configure/basemaps/

I had a few posts about this too, search some older closed CMV issues and you may find it. But the results are posted in the doc link above.

**Comment by carrbrpoa** [comment]
After some trials, there's a new situation now.
Here goes my previous ```mapOptions``` (with *lods* from the last one that worked to the end):

```javascript
mapOptions : {
    basemap : 'osm',
    center : [ -51.18, -30.10 ],
    zoom : 12,
    sliderStyle : 'small',
    lods: [
        , ...
                       {
		                'level': 16,
		                'resolution': 2.38865713397468,
		                'scale': 9027.977411
		            }, {
						'level' : 17,
						'resolution' : 1.0583354500042335,
						'scale' : 4000
					}, {
						'level' : 18,
						'resolution' : 0.5291677250021167,
						'scale' : 2000
					}, {
						'level' : 19,
						'resolution' : 0.26458386250105836,
						'scale' : 1000
					}, {
						'level' : 20,
						'resolution' : 0.13229193125052918,
						'scale' : 500
					}, {
						'level' : 21,
						'resolution' : 0.09260435187537042,
						'scale' : 350
					}, {
						'level' : 22,
						'resolution' : 0.04630217593768521,
						'scale' : 175
					}]
}
```

I found that the baseMap somehow was not liking the values after level 16, so I erased my ```lods``` and just setted ```maxZoom: 19```. Now I can zoom my baseMap further.

PS: to make it clear, the situation was that my operational layers were being successfully rendered after level 16, only the baseMap was not. Now, after the changes, everything goes until level 19, which is fine for me.

The **new problem** now is that printing only prints the baseMap when zoom level <= 16 (my layers are printed in any level).

**Comment by tmcgee** [comment]
Quick not on the original issue: fFor OSM and most ESRI basemaps, 'maxZoom: 19' is not required since that is the default for those maps. Not all of the basemaps go to zoom level 19.  'gray' for example, stops at zoom level 16.

Which basemap(s) do not print? Perhaps you are running into the differences noted in the first paragraph. To test I made a quick change to the demo app configuration. I changed the default basemap to `osm` and set the zoom level to `19` like so:

``` javascript
mapOptions: {
    basemap: 'osm',
    center: [-96.59179687497497, 39.09596293629694],
    zoom: 19,
    sliderStyle: 'small'
},
```
and printed the map multiple times. The basemap was included each time. I tried 'streets' layer as well with the same success.

Are you using your own Print Service or the one included in the demo code:  https://utility.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task?

**Comment by carrbrpoa** [comment]
Hello,

Yesterday I was printing with my own Print Service. Today I tested with ArcGIS one, with the same results. With *streets* basemap, it prints until 2,257 scale (with I think is zoom level 18). It doesn't print the last level (19, scale 1,128) as follows:

![2257](https://cloud.githubusercontent.com/assets/10212618/8874225/487f32a8-31e5-11e5-9beb-3c466be450af.png)
![1128](https://cloud.githubusercontent.com/assets/10212618/8874226/48817270-31e5-11e5-9eec-78f4713502fb.png)

**PS:** The same thing happens with *osm* basemap.

I can open a new issue, if you think it's better.

**Comment by tmcgee** [comment]
Perhaps one of your operational layers is printing white background at that scale? Two thongs to try:

1. Print the same location/zoom/basemap using the demo app http://demo.cmv.io/viewer. 

2. Remove all you operational layers and print the same location/zoom/basemap.

**Comment by carrbrpoa** [comment]
Hey Tim,

Printing on the last possible zoom level prints a blank basemap even in demo app, doesn't matter the location (tried mine and somewhere at USA).

See:

![demo_1128](https://cloud.githubusercontent.com/assets/10212618/8877460/fe700036-31fb-11e5-978c-59a6672ff97c.png)

**Comment by tmcgee** [comment]
Hmmm. This is interesting. I must be missing something obvious. We're getting different results in the demo.

I see from your GitHub profile that you are located in Brazil. I am located near San Franciso. Perhaps geographic region of the user/browser is coming into play? That's a long shot, but possible. Also, what browser are you using? (Perhaps another long shot) I am using the latest version of Chrome browser in a 1024x768 window.

Here's what I just did. Can you follow the same steps and post your results?

1. Opened the demo viewer: http://demo.cmv.io/viewer/
2. Entered `18th St and Oakwood St, San Francisco, CA` into the geocoder and pressed `Enter`.
3. Clicked the `+` until I could zoom in no further..
4. Pressed enter in the geocoder again to re-center the map.
5. Printed using the `Letter ANSI A Portrait` layout.

Here's a screenshot of the app after creation of the PDF:
![image](https://cloud.githubusercontent.com/assets/200780/8877895/f0a8abc0-31dc-11e5-929b-9ab13ff9ee76.png)

Here's a screenshot of the resulting PDF:
![image](https://cloud.githubusercontent.com/assets/200780/8877929/0f57fa30-31dd-11e5-8f68-9ccd15f15b82.png)

Note: I noticed there are more features in the print than in the screenshot. This is a different issue so please ignore that. This is likely due to the limit on features return from the sample FeatureService.

 As an additional test, I also used the geocoder to center on `Sao Paulo, Brazil` and zoomed all the way in. That printed fine as well.


__Hey all you cmv lurkers! :wink: Anybody else got ideas as to what might be up (or down) here?__

**Comment by carrbrpoa** [comment]
You provided a key info now, I guess: Letter ANSI A Portrait layout.
I followed all your steps and everything works fine, but I didn't mentioned that I was trying with A4 (landscape or portrait) layout and none of them prints the basemap! Even A3 does.
The same thing happens in my own application.

**Comment by tmcgee** [comment]
Ok. Now we are getting somewhere! I see those same results (missing basemap) with the other layouts (tried A3 Portrait and A4 Portrait).

Here's what I think is going on. You are attempting to print at the very maximum scale of the basemap. I suspect the PrintService is determining that the basemap is within scale for some layouts (Letter Portrait) and out of scale for other layouts (A3/A4). That probably has something to do with the specific print layouts and map scale. I have zero experience creating layouts on the desktop so can only provide my findings on the web side of things. You can always create your own print layouts in the sizes you want and publish them to AGS. That may help eliminate the issue. That is probably a good practice anyway to include your logos, disclaimers, etc.

**Comment by roemhildtg** [comment]
Just a couple gotcha's when you do create your own layouts: 
* File > Save A Copy... and Choose the version of MXD that your server is using
* Start with the default templates and customize from there, getting the legend to configure correctly can be tricky otherwise
* Follow the esri tutorial step by step, its easy to miss an important detail and have to start over

**Comment by carrbrpoa** [comment]
The main point of the original issue was solved! Thanks for the help!

**Comment by rangasatishkumar** [comment]
@carrbrpoa 
We are also having the same issue of "Print output is blank for last level (Scale 1,128)". Can you please advice.
