### ISSUE TITLE
Tips required: customize left panel

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#474]
Hello,

Is it possible to customize left panel items? I mean by html structural changes, not just CSS stuff.
I see that it uses dbootstrap, but I could not find where the divs are built.

Thanks

**Comment by roemhildtg** [comment]
The title panes on the left are actually "FloatingTitlePanes". The `FloatingTitlePane` is just an extension of the `dijit/TitlePane` class so I believe you could add a `templateString` property to the [FloatingTitlePane](https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/FloatingTitlePane.js#L19) class and override the template with you're own.

**Comment by carrbrpoa** [comment]
Thanks @roemhildtg, your suggestion brought some light! :)

I'll give it a try and then post some example.

**Comment by btfou** [comment]
Templated widgets are easy to alter with a custom template as @roemhildtg suggests. I do this frequently with Dialogs; adding custom content to the containerNode. Be careful that you don't alter the default template's dom structure or attach points to avoid problems.

**Comment by roemhildtg** [comment]
No prob. Just be aware that this will change all of your title panes (which is what I think you want).

**Comment by carrbrpoa** [comment]
Ok guys, I made the changes. I'm not even close to be secure about them, though.
The main goal was to implement the changes suggested by a designer. So, after lots of pain, I ended with this beautiful leftPanel...

![left_panel](https://cloud.githubusercontent.com/assets/10212618/10944003/2afdad12-82fe-11e5-885b-57a281c84ab2.png)

...but I needed to change/create lots of code and CSS ```!important``` stuff. Even *Controller.js* I needed to touch.

Here is a [gist](https://gist.github.com/carrbrpoa/7105f4c8bebfa2c41ed0) with *Controller.js* (minor changes, passing ``category`` prop and pushing leftPanel "footer" logo) and *FloatingTitlePane.js* (massive changes: existent ``createDomNodes`` and ``postCreate`` functions; new ``setTitleBarColors`` and ``_clickCustom`` functions).

I did considered a separated file to treat my changes as a *FloatingTitlePane* mixin, but the changes needed in ``createDomNodes`` worried me.

I need an opinion about all this. Did I do it wrong? There's a more maintenable way? Maybe a *dojo* shortcut that I have no knowledge about? :)

Thanks!

**Comment by tmcgee** [comment]
@carrbrpoa I really like the result. :)

My gut reaction is that the bulk if not all of the custom styling could be done in css. I didn't study every change so I could definitely be off the mark with that comment.

**Comment by carrbrpoa** [comment]
Thanks, good to know @tmcgee!
Well, there are like 150 lines of custom CSS to make this and the main stuff is that my front-end skills (which are not so high) told me that I needed to divide the title pane bar ``div`` into three ``div``s, to make that cropped border between menu items. Smartest and code-less ways to do the same are very welcome! :p

**Comment by roemhildtg** [comment]
I too like the customizations, that's a good look. It would be nice to have the ability to add icons to title panes out of the box perhaps. But I wouldn't recommend modifying your template using dom-construct. 

Instead, copy the [Original TitlePane](https://github.com/dojo/dijit/blob/master/templates/TitlePane.html) template into a new file, lets say in gis/dijit/FloatingTitlePane/templates/CustomTitlePane.html. 

Import your new custom template file using dojo/text!... Add a `templateString` property to the [FloatingTitlePane file](https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/FloatingTitlePane.js) pointed to this string. 

Modify this custom file to your design as far as you can. 

Then, if you want to customize each title pane (like add an icon) [modify the controller to pass those properties into the FloatingTitlePane.](https://github.com/cmv/cmv-app/blob/master/viewer/js/viewer/Controller.js#L419-L435) You can access them in your template using something like 

`class="${cssClass}" ...`

In this example, the controller would have to add a cssClass to the options passed to FloatingTitlePane.

**Comment by carrbrpoa** [comment]
Seems promising Gregg, thanks! I will take a closer look tomorrow ;)

**Comment by tmcgee** [comment]
@carrbrpoa Not sure if I captured all of your styling but I think I got a good portion:

``` css
#identify_parent, #find_parent {
    border-left: 10px solid blue;
    -webkit-border-radius: 0;
    border-radius: 0;
    background-color: white;
}

#identify_parent .dijitTitlePaneTextNode,
#identify_parent .dijitArrowNode,
#find_parent .dijitTitlePaneTextNode,
#find_parent .dijitArrowNode {
    color: red;
}

.dijitTitlePaneTitle:hover {
    font-weight: 700;
}
```

The line below the titlePane is certainly a challenge. I think @roemhildtg's suggestion of creating a template will give you the additional divs to style the way you would like.

Icons can be added with css too:

``` css
.dijitTitlePane .dijitTitlePaneTextNode:before {
    font-family:'FontAwesome';
    margin-right: 8px;
}

#find_parent .dijitTitlePaneTextNode:before {
    content: '\f002';
}
```

Can you tell I am a big proponent of separating style from code wherever possible. :)

**Comment by carrbrpoa** [comment]
Hello guys!

Thanks everyone for the tips. I reunited your powers and did something a lot more maintainable, with exactly the same look. :100: 

Here's a new [gist](https://gist.github.com/carrbrpoa/4cf2e96b31d35b7a5f84) (look for ``//Custom`` comments in js files).

I could not avoid some custom javascript code in ``FloatingTitlePane.js`` like ``setIconHoverColors`` function to "cascade" the hover to title pane icons and ``_clickCustom`` to mimic the arrow for closed and opened panel behavior, tied with some ``aspect`` stuff.

PS: @roemhildtg, just after your [fast tutorial](https://github.com/cmv/cmv-app/issues/474#issuecomment-153863534) I fully understood what you and @btfou were talking about in the beggining of the issue :)

**Comment by tmcgee** [comment]
@carrbrpoa To make you code even more maintainable, consider extending the `FloatingTitlePane` widget class just as it extends the `TitlePane` widget class. Then you only need to include your new methods and the one or two that need to be overridden. In the overridden methods,  you can likely call `this.inherited(arguments)` to avoid duplicated code.

The same would apply to Controller though I might consider that class a bit differently. In a recently submitted PR, I separated the Controller into Mixins. This would allow you to add a [custom Mixin](https://github.com/cmv/cmv-app/blob/feature/controller-with-mixins/viewer/js/config/app.js#L34) that only included the two methods that you modified.

I have experimented with this mixin concept with custom mixins to:

1. Use [bootstrap-map-js](https://github.com/Esri/bootstrap-map-js) for the page/sidebar layout instead of BorderContainer.

2. Use the new JS API version 4 beta 1 to instantiate the map (including 3D) and add layers

Both of those mixins include only a few new and override methods.

Feedback on this concept is most welcome.

**Comment by ERS-Long** [comment]
Beautiful layout, just want to play your approach so i i tried your layout, for some reason, there is some issue with my layout,  The header got split into two rows. please let me know how to fix it.

Thanks 

![image](https://cloud.githubusercontent.com/assets/5911272/10988957/e561cfa4-8406-11e5-8d48-98ca3263cdbb.png)

**Comment by carrbrpoa** [comment]
Hey @ERS-Long, my mistake. I forgot to add some new stuff to my ``styleHack.css``. Check the news in the [updated gist](https://gist.github.com/carrbrpoa/4cf2e96b31d35b7a5f84).

**Comment by ERS-Long** [comment]
Thanks @carrbrpoa a lot, got it working!

**Comment by tmcgee** [comment]
@carrbrpoa 

I can see a PR coming out of this group effort if it is made a little bit more generic. Here are 2 thoughts:

* Pass a `className` from Controller to FloatingTitlePane instead of a `category` then add that className to the TItlePane. The resulting dom element would then look something like:

```
<div class="dijitTitlePane TitlePaneSearch" id="find_parent" widgetid="find_parent">
   ...
</div>
```

* In FloatingTItlePane, instead of setting specific colors based on `category` for Title, Arrows, Icons, I would toggle css class(es).

These further remove the styling from the code and would allow other devs to use or completely ignore these customizations.

**Comment by carrbrpoa** [comment]
I think you have a good point, @tmcgee. Could be very nice to have this possibility in a more generic way.
The reason that I kept that style in code was that I wanted to apply the hover effect of ``titleBarNode`` to the icon too (without hovering the icon), but I didn't manage to do it just with CSS. :)

**Comment by tmcgee** [comment]
@carrbrpoa yep. I understand the objective. Instead of using this code:

``` javascript
domStyle.set(icon, { 'color': color });
```
you could use something like:

``` javascript
domClass.toggle(icon, 'hover');
```

OR

``` javascript
domClass.add(icon, 'hover');
domClass.remove(icon, 'hover');
```

Then css classes would be something like:

``` css
.TitlePaneSearch i {
  color: blue;
}
.TitlePaneSearch i.hover {
  color: red;
}
```

If you include those css classes, you will get the color change on hover. If I did not have the classes, there would be no change. All with the same base JS code.

Another suggestion: Your approach to icons is based on the `<i>` included in the title. Personally I would do that in css like I provided earlier. Then your same css file can be utilized with multiple applications to achieve a common style. If you decide to change the "find" icon in the future, change it in one place (css) instead of the "Find" tile each and every application's viewer.js.

**Comment by carrbrpoa** [comment]
Great Tim! I agree and will aggregate it soon! Thanks for the help! ;)

**Comment by tmcgee** [comment]
@carrbrpoa If you have any additions, please update this discussion. closing the issue.
