### ISSUE TITLE
Identify pop up to acts as a file browser

### ISSUE THREAD

**Issue by stillwolly2013** [cmv/cmv-app#524]
meetupHometowns:{
            0:{
               
                description:"<b>Related Documents</b>:  anchor file directory

meetupHometowns:{
            0:{
                title: '{Prov_Name}',
                description:"<b>Related Documents</b>: <a href='file:///W|/7_users/712_Walter/'>Document</a><br />",
                mediaInfos: [{
                    title: '',
                    caption: '',
                    type: 'image',
                    value: {
                        sourceURL: 'http://bugatti.nvfast.org/Snapshots/{Id}.jpeg?r='+new Date().getDate,
                        linkURL: 'http://bugatti.nvfast.org/Snapshots/{Id}.jpeg?r='+new Date().getTime()
                    }
                }]

                }
            },

**Comment by tmcgee** [comment]
@stillwolly2013 I'm not exactly sure what you are looking for. Can you add more details to clarify your issue/objective.

**Comment by stillwolly2013** [comment]
@tmcgee i want to set a hyperlink to the identify widget descript that looks for for specific folder or directory on a network  e.g like below


![tim](https://cloud.githubusercontent.com/assets/9570879/14160127/9d93dd1e-f6ef-11e5-8654-c9e3c788c375.png)
![tim2](https://cloud.githubusercontent.com/assets/9570879/14160130/a1cbf9a2-f6ef-11e5-8764-804bca269c50.png)

**Comment by kcarrier** [comment]
@stillwolly2013 - I would caution against this approach, this functionality works differently in each browser because in many respects it as viewed as a security risk. The better option in my opinion would be to setup a virtual directory in IIS. Then you would enable directory browsing so they could path through a folder in a web browser like in windows explorer, although this is also seen to some as a security risk as well. Either way virtual directories will work better across all browsers than network paths in my experience. If a virtual directory is not an option then use the firefox example as that path structure works across all 3 browsers.

For example;

Chrome:
\\servername\folder --> file://servername/folder/

Firefox:
\\servername\folder --> file://///servername/folder/

IE:
\\servername\folder --> Opens in windows explorer

**Comment by stillwolly2013** [comment]
@kcarrier  what if the users are authenticted through LDAP? am using arcgis server

**Comment by tmcgee** [comment]
@stillwolly2013 Virtual directories in IIS support authentication through Active Directory/LDAP. The net effect is only those users authenticated through Active Directory would have access to those directories.

**Comment by stillwolly2013** [comment]
@tmcgee the client does not want to duplicate the information....so whats the option i should go for ?

**Comment by tmcgee** [comment]
@stillwolly2013 Not knowing your network, file structure and web server setup, I really can't provide any options or additional support. This discussion is about web server configuration and outside of CMV project so I am going to close this issue. Perhaps this question is better asked at stackoverflow or a stackexchange community.
