### ISSUE TITLE
Server workload using ArcGIS Server

### ISSUE THREAD

**Issue by blee07** [cmv/cmv-app#620]
Hi all, I have a few questions regarding the workload CMV has on the server and if there are any limitations. I work at a large company and if we proceed to use this application there could be hundreds of users. The viewer I have configured now is using ArcGIS Server rest services. Are there any limits on the amount of users?  I love what I've seen so far from CMV. I want my company to use it but do not want to start using is and it not being able to handle the workload of users. As of now I am only using map services and not feature services so no edits. But, I would like to have an editable application as well but it would not have as many users. Still, would there be any limitiations? Also, does using and GP services bog down the server? I appreciate all your help as I am new to CMV. Thank you!

**Comment by roemhildtg** [comment]
CMV won't put any extra load on the server as opposed to any other web map. You can use IIS to serve the cmv folder, which should have very little impact on your server performance since the [Esri API is loaded from the cdn](https://github.com/cmv/cmv-app/blob/develop/viewer/index.html#L53) (content delivery network). 

I don't have much experience with that many users but it seems to me that might be a scenario where you would have multiple arcgis servers set up, each with the same services, and then use a load balancer to distribute the requests. Again, this isn't particular to CMV, its true for any web map or native app. Then you point your cmv app to the load balancer proxy to distribute your thousands of users' requests.

GP Services, like printing, are pretty inefficient (IMHO), and yes, they do have the potential to bog down the server, depending on what they are doing. Essentially, they are like running a python tool on the desktop, but in the background on the server. If a lot of people are using these services then having multiple servers would help. 

My advice: 
 - Use Tiled services where possible. These layers are cached static content so they don't need to be generated on the fly. But they don't support "Identify" operations.
 - Keep symbology simple (especially labeling) that will help with performance. 
 - As an alternative to GP services, sometimes its more efficient to run processes client side. Buffering and other geometry operations, file exporting, and even [simple pdf generation](https://github.com/MrRio/jsPDF) can now be done using pure javascript.

**Comment by tmcgee** [comment]
@blee07 I have a number of clients using CMV that have between ~100 and ~500 users using dozens of applications. I am aware of other organizations that have successfully implemented CMV for larger organizations.  As mentioned by @roemhildtg, CMV itself has minimal impact on the server. There are many techniques to optimize the delivery of CMV and other web assets though I suggest you focus first on ensuring the ArcGIS Server(s) and the Enterprise database server(s) hosting the data are scalable. Esri has a number of tools for planning and measuring performance.

**Comment by blee07** [comment]
Thank you both!
