### ISSUE TITLE
quetion for Help widget

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#630]
Hello, CMV team, How to make Help link to a iFrame or modal box. after click a text in the help list, display a iframe or modal box on the top of index.html or map. Thanks!

**Comment by roemhildtg** [comment]
Are you asking about the help widget included in the cmv app? You could modify the help template to load your iframe instead of what its currently loading. 

Better yet, since the help widget uses `dijit/layout/ContentPane` you can actually provide it an `href` property which it will load a web page asynchronously in the background which will result in a better load time. 

To provide a `href` property, modify your help template content panes to something like this: 
```html
<div data-dojo-type="dijit/layout/ContentPane" title="${i18n.navigation.title}" data-dojo-props="href: 'js/gis/dijit/Help/templates/help.html'">
```

**Comment by JudyZhou** [comment]
thanks @roemhildtg . I am not sure this code can make the linked page display at iFrame. I added hyperlink to HelpDialog.html inside of <li> tag, but it is not iFrame. I am afraid if I add iFrame in it, it is going to display inside of Help pane.

**Comment by roemhildtg** [comment]
You're going to have to be more specific. It would help if you posted the code that you tried. The code I posted will load an html file into a content pane, without using an iframe.

**Comment by roemhildtg** [comment]
@JudyZhou were you able to get this working?
