### ISSUE TITLE
urgent: my location does not work

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#631]
I even test the link you provided, http://demo.cmv.io/viewer/, My Location widget doesn't work. Could you please help?

**Comment by tmcgee** [comment]
@JudyZhou Please read the [relevant paragraph]](https://developers.arcgis.com/javascript/3/jssamples/widget_locate.html) about browser security in the locator Button documentation and this [Esri blog post](https://blogs.esri.com/esri/arcgis/2016/04/14/increased-web-api-security-in-google-chrome/). That is the most likely cause affecting your site. It definitely does affect the demo site because it is not using HTTPS.

**Comment by JudyZhou** [comment]
@tmcgee  ESRI Web AppBuilder works with My Location.

**Comment by tmcgee** [comment]
@JudyZhou The Web AppBuilder and CMV both use the Esri Locator Button dijit so something else must be effecting this. A few questions for you to review to help you determine the issue:

1. Are the WAB app and the CMV app on the same server (server name, port and protocol)?
2. What version of the Esri JavaScript API are you using for WAB and for CMV?

**Comment by JudyZhou** [comment]
on the same server. once I run my location button in WAB app viewer, it is kind of triggered, then CMV locator start working.

**Comment by tmcgee** [comment]
that's odd. that sounds like a browser permission thing for location services.
