### ISSUE TITLE
Side effect of custom fields formatters in Identify

### ISSUE THREAD

**Issue by tmcgee** [cmv/cmv-app#650]
@roemhildtg I think we may want to reconsider the approach we worked on for #618. Changing the [attributes of the original feature](
https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/Identify.js#L339) is liekly not a desirable outcome.  For example, if you have code elsewhere that does this: 

``` javascript
var feature = this.map.infoWindow.getSelectedFeature();
```

you get a result that you might not expect. What is returned will have modified attributes based on the formatters, not those of the original feature. 

I ran into this in a current application. Capturing it here for review and discussion. No immediate solution comes to mind.

**Comment by roemhildtg** [comment]
I see the issue, and the thought had crossed my mind earlier. I agree it could definitely be an undesirable side-effects.

Off the top of my head, one solution I see is to build a default `content` formatter property for each identify layer in the identify widget. 

```javascript
function getContentFormatter(args){
  return function(attributes){
    // getFormattedAttributes will return the attributes and apply any formatters
    // it can also remove properties that have `include: false` or we could implement 
    formattedAttributes = getFormattedAttributes(lang.clone(attributes), args.fieldInfos);

    //getTableHtml will iterate through the attributes and create a row
    return getTableHtml(formattedAttributes);
  }
}
```

and then

`popup.setContent(getContentFormatter(this.identifies[layerid][sublayer_id])`

**Comment by roemhildtg** [comment]
I don't think there's really a great solution to this that doesn't result in a lot of redundancy. The solution I mentioned above wouldn't work well since we'd have to replicate the functionality of the popup parts when there is no content function (title, fieldInfos, attachments, etc...)

Another solution would be to put the original cloned attributes in an extra property like `feature.originalAttributes` but I don't see the real benefit there since we're renaming the property and much of the api that would use the `attributes` property anyways. 

Perhaps the best solution is to warn people, and if they need the original value, create instead a virtual field with a formatter and exclude the other field from the identify popup.

**Comment by tmcgee** [comment]
@roemhildtg I agree. Using virtual fields with a formatter is how I work around this and it meets all my requirements so far. I think some info in the docs alerting folks to the potential pitfalls is the way to go.
