### ISSUE TITLE
New Authentication/Authorization mechanism

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#673]
I'm planning to integrate Keycloak (enterprise's SSO) with ArcGIS token-based auth, aiming for unique and smoothless authentication.
The initial flow planned is something like this:

- Implements Keycloak stuff in CMV;
- The user enters the application then Keycloak takes control for login, etc.;
- CMV could be loading some secure services, so, in these cases I would like to intercept it's default mechanism that prompts the user for credentials and call some backend that somehow takes the previously supplied credentials and do the auth in ArcGIS, without user intervention.

Any tips for the last item? Basically, I think I wish to suppress `IdentityManager` completely, or something like this. And does it impacts feature edition that registers the creator/updater user?

Thanks!

**Comment by tmcgee** [comment]
@carrbrpoa I am not familiar with Keycloak though have done similar things using web-tier authentication both with SSO providers and home-grown systems using username/passwords stored in a db. Using web-tier authentication stops the user from accessing the application before they can get to any resources associated with the application. Requesting credentials once you've already accessed the application like the IdentityManager does is too late in my opinion.

To my knowledge, AGS does not support SSO for authentication so with the web-tier, you must use Active Directory or an LDAP provider. That was not an option for many of the implementations I worked with. Instead, we choose to control access to data in AGS by using the Esri resource proxy using a token pre-assigned by AGS. Access to the resource proxy url is also handled by the web-tier so no direct access to the data . With this approach, no changes to CMV or the Esri JS API are required.

For Feature editing, we implemented a second set of fields in the data to track the SSO username that created and modified the records. That was far easier than trying to integrate the SSO provider with the AGS user system by mirroring the usernames in both systems. We didn't pursue this very far due to time limitations. There may be a better solution to track the users.

I hope this gets you moving in the right direction. Unless there are CMV-specific modifications or requirements, this is probably best discussed further outside of this repo.

**Comment by carrbrpoa** [comment]
Hey @tmcgee!
Thanks for your considerations!
I'll think about the other possibilities you mentioned.

A little more of context: both our SSO and our AGS auth relies in AD, so my goal was to implement some "glue" to them, initially to work with CMV.

I think that doing it correctly (generating token for user / traffic it when needed), feature editing would be automatically solved (correct me if I'm wrong).

Considering that, is it possible to intercept that _ask for credentials_ so that whenever CMV / ERSI API detects that credentials are needed and asked for it, I could do something before, like redirecting to my "glue" stuff instead?

**Comment by tmcgee** [comment]
If AGS auth relies on AD (presuming web-tier authentication via the web adapter), why the need/use of tokens?

**Comment by carrbrpoa** [comment]
Because it is what is done in `IdentityManager` or even when we access AGS admin, I guess. Always have some token exchange. So I thought that was the way, using AGS API for token acquisition (with AD user and pass) to authenticate the user by myself and do the custom stuff needed.

**Comment by tmcgee** [comment]
I think (but not 100% certain) that tokens are only used for GIS-tier authentication (web adapter or direct to REST end-point), not web-tier authentication through the web adapter.

**Comment by carrbrpoa** [comment]
![image](https://cloud.githubusercontent.com/assets/10212618/23222256/12841850-f906-11e6-8436-c60309006312.png)

**Comment by tmcgee** [comment]
so that request is accessing the web adapter with web-tier authentication (AD) not gis-tier authentication (token-based)?

**Comment by carrbrpoa** [comment]
I'm not sure of the response. Actually, I'm having trouble with the communication of keycloak and AGS; seems I can't take advantage of the password previously informed to generate the token. So maybe now this issue is 100% out of CMV field :p

**Comment by tmcgee** [comment]
you're certainly getting out of my field - at least with what assistance I can provide through github...

**Comment by carrbrpoa** [comment]
Thanks @tmcgee, you can close it if you wish.

**Comment by tmcgee** [comment]
@carrbrpoa Let me know how it works out.
