### ISSUE TITLE
cmv-app advanced spatial search crashes

### ISSUE THREAD

**Issue by FedwaSlimani** [cmv/cmv-app#731]
when I do a spatial search with a large buffer or large circle the application crashes and stop working, it gives me an error (Oups AIE AIE) in chrome. any help please.

**Comment by tmcgee** [comment]
@FedwaSlimani I'm not sure the widget is specifically to b!ame. It sounds like the browser cannot handle displaying that much information on the map. 

You do not mention of what type of features the search is returning. If they are polygons, consider generalizing (simplifying) the number of points in each polygon. This can be done in the data before loading it into ArcGIS Server. In addition, depending on the version of AGS, Esri allows you to add the `maxAllowableOffset` parameters to the search to generalize the results. I don't know if that widget supports this {it is a bit dated now}. I do support that parameter in my search widget/attributes table widgets. Here is an example config file that demonstrates this. https://github.com/tmcgee/cmv-widgets/blob/master/config/table.js#L70

**Comment by FedwaSlimani** [comment]
@tmcgee First of all thank you for your quick answer
I am using points not polygons, the total number of points that i have on the map is 450 so it's a little bit weird that the application crashes ! the browser i am using is the last version of chrome. bellow a picture of the error i got when i draw a large circle.
![bug_spatial_search_with_circle_0](https://user-images.githubusercontent.com/28005520/27206722-c6b4b2d2-5228-11e7-8001-babf9afca36f.png)
![bug_spatial_serach_with_circle](https://user-images.githubusercontent.com/28005520/27206746-d319a0a0-5228-11e7-8984-59033f4db380.png)

**Comment by FedwaSlimani** [comment]
@tmcgee hope that you help me solving this problem, because the application still crashes !!

**Comment by tmcgee** [comment]
@FedwaSlimani Points should not be a problem until you get to 10s of thousands. Possibly it isn't even getting to the search request and crashes drawing the circle?

The best I can suggest is to try this same search with the latest version of my [Search and AttributesTable widgets](https://github.com/tmcgee/cmv-widgets). If it still crashes, that gives me better options to help troubleshoot since I am more familiar with my own code. :smile:

**Comment by drusexton** [comment]
@FedwaSlimani I have been having issues with the advanced search widget and CMV 2.0 for several weeks. I have been experiencing this exact issue as well. I have delved into the code and tried to fix the issues. However I got busy with other tasks and had to put this on hold, then I broke my arm rather terribly. Anyhow I am no expert, developer, but it appears like @tmcgee said, that this tool is pretty old. I think its based off older API, and some the functions have changed. I will continue to follow this thread and then next week I will get to the office and my colleague can help me contribute.

**Comment by FedwaSlimani** [comment]
@tmcgee 
i have two questions : the first is about the attributes search, how to remove attibuts from the widget and let just spatial
the second question is can we keep the advanced search and attributes search both of them in one viewer ?

**Comment by FedwaSlimani** [comment]
@tmcgee i am waiting for your answer please

**Comment by tmcgee** [comment]
@FedwaSlimani Yes, you can set my Search widget up to show only the Spatial tab. Just include this is your configuration for the widget:
``` javascript
defaultTab: 1,
hiddenTabs: [0],
```

As to whether the "Advanced" search widget and my search widget can be used together in one viewer, I don't know since I don't use or support the other widget. You will have to try that for yourself.
