### ISSUE TITLE
Highlight polygon features when searching with Geocoder

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-app#759]
When using the Geocoder/search bar, is there a straightforward way to highlight polygon features (i.e., parcels) after the search has been executed?  I was able to add a point to the feature, but that doesn't help when or if multiple polygons are returned.  I've attached an image/example from the Flex Viewer days :)

I've found that the "Find" widget would do the trick, but in the business of keeping it simple, I'd like to achieve similar results with the Geocoder.

Thanks,

Jesse

![flexsearch](https://user-images.githubusercontent.com/16945459/29131064-3fecdf88-7cf1-11e7-8625-ed2a8559fee0.PNG)

**Comment by tmcgee** [comment]
@JhopStl The older Geocoder widget (deprecated by Esri) and the newer [Search widget](https://developers.arcgis.com/javascript/3/jsapi/search-amd.html) are both Esri widgets. I don't think the Search widget supports highlighting multiple results out of the box.

One of my future objectives is to create a combined one-stop-shop search with a simple UI that combines the geocoding of Esri's Search widget with my [Search](https://github.com/tmcgee/cmv-widgets#search) and [AttributesTable(s)](https://github.com/tmcgee/cmv-widgets#attributes-tables) widgets (I named mine `Search` before Esri. :wink:). My widgets already do everything the CMV Find widget does so that part is covered. This may get accomplished via some work I doing for a client that can be shared back to the CMV community. I don't know if or when that might come together as it is tied to much larger objectives with the client.

**Comment by JhopStl** [comment]
@tmcgee That's unfortunate. However, looking closer at the Find widget, I think I can make this work for what I need to do.  As always, I appreciate all the work you do on the CMV project!
