### ISSUE TITLE
Pane Issue

### ISSUE THREAD

**Issue by gisnovice** [cmv/cmv-app#763]
__Description:__

I want to add a content block that will always show up, but not in a widget on the left pane; however, when I do this it the block appears on the top instead of the bottom. In 2.0.0-beta1 this code work, but now it does not. How would I fix it?

`panes: {`
            `left: {},`
           ` myContent: {`
               ` id: 'myContent',`
                `placeAt: 'left',`
                `region: 'bottom',`
               ` style: 'height: 220px !important;overflow:hidden',`
               ` content: 'SOMETHING SOMETHING'`
            `}`
       ` },`

![cmv](https://user-images.githubusercontent.com/26489280/29592477-278ae2b0-8759-11e7-8c1b-59311d0a9ad2.png)

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 2.0.0-beta 2
| Browser                 | I.E. / Chrome
| Operating system | Windows 10

**Comment by tmcgee** [comment]
@gisnovice I see what you mean. This is surprising since there have been only 2 minor changes directly related to panes since beta 1.  In addition, CMV doesn't use the `region` property - it is is specific to dojo layout dijits. I am not clear why that is being ignored.

Slightly more complicated but here is an alternative approach that works:

``` javascript
panes: {
    outerLeft: {
        id: 'sidebarLeft',
        type: 'border',
        region: 'left'
    },
    myContent: {
        id: 'myContent',
        placeAt: 'outerLeft',
        region: 'bottom',
        style: 'height: 220px !important;overflow:hidden;border:0',
        content: 'SOMETHING SOMETHING'
    },
    left: {
        id: 'leftCenter',
        placeAt: 'outerLeft',
        style: 'border:0;padding:0',
        region: 'center'
    }
},
```

![image](https://user-images.githubusercontent.com/200780/29598959-6ca708ce-8781-11e7-8aab-77192b37950a.png)

**Comment by gisnovice** [comment]
Also since the pane doesn't really close anymore with this fix, how would I take off the slider, @tmcgee ?

**Comment by tmcgee** [comment]
Use `collapsible: false`
