### ISSUE TITLE
Map View/Layer List Question

### ISSUE THREAD

**Issue by drusexton** [cmv/cmv-app#765]
@tmcgee @roemhildtg @DavidSpriggs Does anyone know if it is possible to include a map service or layer on your map, but exclude it from the Layer List and Legend?

**Comment by tmcgee** [comment]
@drusexton the `exclude` option for a layer is documented [here](http://docs.cmv.io/en/latest/configure/operationalLayers/) for the Legend, Editor and Identify widgets and separately [here](http://docs.cmv.io/en/latest/widgets/LayerControl/) for the layerControl widget since it has more configuration options.

**Comment by drusexton** [comment]
@tmcgee Thanks!
