### ISSUE TITLE
Problem with the add attachment in EDIT?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#868]
Problem with the add attachment with version?. I have a old version of the cmv install in 2014 I don't have the numerous of that one??? 
But I am not able to add attachment in that one ...TAKE A LOOK OF THE SCREEN SHOT
![image](https://user-images.githubusercontent.com/6784515/48225292-5ceeea00-e36a-11e8-9127-b7a074a0af20.png)

And with the other version cmv2.0 it work TAKE A LOOK OF THE SCREEN SHOT 
![image](https://user-images.githubusercontent.com/6784515/48225318-6ed08d00-e36a-11e8-8f02-d987fd349a08.png)

do you think there is a way to don't remake every thing to the version 2.0 to repair that old version???
Thank in advance for your answer!

**Comment by tmcgee** [comment]
@GilbertLasnier The second screenshot shows shows the identify window not the editor. I'll assume you included the wrong screenshot. Any differences in the Add Attachment functionality would not likely be due to CMV since it is the Esri Editor widget. This would most likely be some a configuration issue or compatibility between the version of Esri API and the version of ArcGIS Server you are using.
