### ISSUE TITLE
Identify conflicts with Draw widget after Navigation Tool added ?

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-app#901]
Hi,

Identify widget (map click) conflicts with Draw widget, also identify widget map click  on map and display popup info, If You add Navigation toolbar widget.

If I set include : false in Viewer.js file and don't add the widgets then its not conflicting the widget.
Navigation Widget is here : 

https://github.com/friendde/ArcGIS_JS_NavigationTools/blob/master/NavTools.js

After adding Navigation widget :

![identify](https://user-images.githubusercontent.com/6058868/56276644-8b3bd700-610b-11e9-8313-19084428f964.gif)

If you don't add navigation widget : 

![identify1](https://user-images.githubusercontent.com/6058868/56276789-d524bd00-610b-11e9-8150-4d33eade1e78.gif)

Thanks,

**Comment by tmcgee** [comment]
@mayur9785 That issue with the Navigation widget has been around for a long time due to the way it was written. Not sure if it is still supported by the developer. I may have a copy of that widget that I fixed/upgraded years ago for a client. I'll see if I can track it down. Since this issue is not directly related to CMV core, I am going to close it.

**Comment by tmcgee** [comment]
If I recall corectly, this has to do with how the Esri [Navigation toolbar](https://developers.arcgis.com/javascript/3/jsapi/navigation-amd.html) used in the contributed Navigation widget interacts with the underlying map.

**Comment by mayur9785** [comment]
@tmcgee,
Thank you so much for your reply.
All the business and end users would like to see the navigation widget in app as per the requirement.
I will be grateful to you if you can share your navigation widget working with current CMV version.
Thanks,
